_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
data_path:
    value: ../crawler/downloads/
image_dir:
    value: ../crawler/downloads/images/
learning_rate:
    value: 0.001
model_name:
    value: resnet18
num_epochs:
    value: 20
risk_type:
    value: diseases
seed:
    value: 42
validation_split:
    value: 0.2
weight_decay:
    value: 1e-05
