wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3735021602108979
learning_rate:
  value: 1.0002216941038136
model_name:
  value: resnet34
num_epochs:
  value: 15
validation_split:
  value: 0.2
weight_decay:
  value: 1.0096563460935497
