apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-server-custom-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-server
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Pods
    pods:
      metric:
        name: inference_requests_per_second
      target:
        type: AverageValue
        averageValue: 100
  - type: Pods
    pods:
      metric:
        name: inference_latency_p95
      target:
        type: AverageValue
        averageValue: 500m  # 500 мілісекунд
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: model-server
      metric:
        name: requests_per_second
      target:
        type: Value
        value: 1k  # 1000 запитів на секунду
