_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 8
data_path:
    value: ../crawler/downloads/
dropout:
    value: 0.3
freeze_epochs:
    value: 3
gradual_unfreezing:
    value: false
image_dir:
    value: ../crawler/downloads/images/
image_size:
    value: 224
label_smoothing:
    value: 0.05
learning_rate:
    value: 0.001
model_name:
    value: mobilenet_v2
num_epochs:
    value: 30
patience:
    value: 8
progressive_resizing:
    value: false
risk_type:
    value: diseases
seed:
    value: 42
use_cosine_annealing:
    value: false
use_cutmix:
    value: false
use_focal_loss:
    value: false
use_mixup:
    value: false
use_tta:
    value: false
validation_split:
    value: 0.3
weight_decay:
    value: 0.0001
