experimentName: distilbert-hyperparam-search
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
searchSpace:
  learning_rate:
    _type: choice
    _value: [1e-5, 2e-5, 3e-5]
  batch_size:
    _type: choice
    _value: [8, 16]
  epochs:
    _type: choice
    _value: [3, 4]
  weight_decay:
    _type: choice
    _value: [0.01, 0.1]
tuner:
  builtinTunerName: TPE
trial:
  command: python nni_search.py
  codeDir: .
  gpuNum: 0