# Конфигурация для эксперимента MosaicBERT

# Аргументы модели
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 512
type_vocab_size: 2
initializer_range: 0.02
vocab_size: 30522
use_alibi: true
use_flash_attention: false

# Аргументы данных и обучения
dataset_name: "wikitext"
dataset_config_name: "wikitext-103-raw-v1"
max_seq_length: 512
mlm_probability: 0.15
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
learning_rate: 5e-4
weight_decay: 0.01
warmup_steps: 10000
num_train_epochs: 40.0
max_steps: -1
logging_steps: 500
save_steps: 10000
eval_steps: 5000
output_dir: "./mosaic_bert_output"
