_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
dropout:
    value: 0.5932446166852652
learning_rate:
    value: 0.000988752644575166
model_name:
    value: resnet18
num_epochs:
    value: 20
validation_split:
    value: 0.2
weight_decay:
    value: 7.888957829732234e-05
