_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 16
data_path:
    value: ../crawler/downloads/
dropout:
    value: 0.5
freeze_backbone_epochs:
    value: 5
image_dir:
    value: ../crawler/downloads/images/
label_smoothing:
    value: 0.1
learning_rate:
    value: 0.0001
model_name:
    value: mobilenet_v2
num_epochs:
    value: 50
patience:
    value: 10
risk_type:
    value: diseases
seed:
    value: 42
validation_split:
    value: 0.25
weight_decay:
    value: 0.001
