wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.13424339495441837
learning_rate:
  value: 0.0025668660844411022
model_name:
  value: mobilenet_v2
num_epochs:
  value: 20
validation_split:
  value: 0.3
weight_decay:
  value: 6.339577481794106e-05
